#define _GNU_SOURCE

#include "runtime.h"
#include "cpuid.h"
#include "syscall.h"
#include "kuser.h"
#include "registry.h"

#include <dlfcn.h>
#include <errno.h>
#include <signal.h>
#include <stddef.h>
#include <string.h>

typedef int (*sigaction_fn)(
    int,
    const struct sigaction *,
    struct sigaction *
);

static sigaction_fn real_sigaction;

static struct sigaction saved_sigsegv;
static struct sigaction saved_sigsys;

static int have_sigsegv;
static int have_sigsys;

static void linuwux_segv_wrapper(
    int signum,
    siginfo_t *info,
    void *ucontext);

static void linuwux_sigsys_wrapper(
    int signum,
    siginfo_t *info,
    void *ucontext);

static void resolve_sigaction(void)
{
    if (real_sigaction)
        return;

    real_sigaction = (sigaction_fn)dlsym(RTLD_NEXT, "sigaction");
}

static int is_special_signal(int signum)
{
    return signum == SIGSEGV || signum == SIGSYS;
}

static int action_has_real_handler(const struct sigaction *act)
{
    if (!act)
        return 0;

    if (act->sa_flags & SA_SIGINFO)
    {
        return act->sa_sigaction != NULL;
    }

    return act->sa_handler != SIG_DFL &&
           act->sa_handler != SIG_IGN &&
           act->sa_handler != NULL;
}

static struct sigaction *saved_action_for_signal(int signum)
{
    if (signum == SIGSEGV)
        return &saved_sigsegv;

    if (signum == SIGSYS)
        return &saved_sigsys;

    return NULL;
}

static int *saved_flag_for_signal(int signum)
{
    if (signum == SIGSEGV)
        return &have_sigsegv;

    if (signum == SIGSYS)
        return &have_sigsys;

    return NULL;
}

static void (*wrapper_for_signal(int signum))(
    int,
    siginfo_t *,
    void *)
{
    if (signum == SIGSEGV)
        return linuwux_segv_wrapper;

    if (signum == SIGSYS)
        return linuwux_sigsys_wrapper;

    return NULL;
}

static int kernel_action_is_our_wrapper(
    int signum,
    const struct sigaction *act)
{
    void (*wrapper)(int, siginfo_t *, void *);

    if (!act)
        return 0;

    if (!(act->sa_flags & SA_SIGINFO))
        return 0;

    wrapper = wrapper_for_signal(signum);

    return wrapper &&
           act->sa_sigaction == wrapper;
}

static void chain_saved_action(
    const struct sigaction *saved,
    int have_saved,
    int signum,
    siginfo_t *info,
    void *ucontext)
{
    if (!have_saved)
        return;

    if (saved->sa_flags & SA_SIGINFO)
    {
        if (saved->sa_sigaction)
            saved->sa_sigaction(signum, info, ucontext);

        return;
    }

    if (saved->sa_handler == SIG_IGN)
        return;

    /*
     * We intentionally do not attempt to emulate SIG_DFL here.
     * A default disposition is never wrapped by sigaction(), so
     * reaching this case would indicate inconsistent internal state.
     */
    if (saved->sa_handler == SIG_DFL ||
        saved->sa_handler == NULL)
        return;

    saved->sa_handler(signum);
}

static void linuwux_segv_wrapper(
    int signum,
    siginfo_t *info,
    void *ucontext)
{
    /*
     * Milestone 2:
     * handle CPUID faults generated by ARCH_SET_CPUID ourselves.
     * All unrelated SIGSEGV signals still go to Wine unchanged.
     */
    if (linuwux_cpuid_handle_sigsegv(info, ucontext))
        return;

    chain_saved_action(
        &saved_sigsegv,
        have_sigsegv,
        signum,
        info,
        ucontext
    );
}

static void linuwux_sigsys_wrapper(
    int signum,
    siginfo_t *info,
    void *ucontext)
{
    /*
     * LinUwUx syscall redirect.
     *
     * If the context was transformed successfully, execution resumes
     * at TargetSysHandler. Otherwise Wine receives the original SIGSYS.
     */
    if (linuwux_syscall_handle_sigsys(ucontext))
        return;

    chain_saved_action(
        &saved_sigsys,
        have_sigsys,
        signum,
        info,
        ucontext
    );
}

LINUWUX_EXPORT int sigaction(
    int signum,
    const struct sigaction *act,
    struct sigaction *oldact)
{
    struct sigaction wrapped;
    struct sigaction kernel_old;
    struct sigaction previous_saved;
    struct sigaction *saved;
    int *have_saved;
    int previous_have_saved;
    int ret;

    resolve_sigaction();

    if (!real_sigaction)
    {
        errno = ENOSYS;
        return -1;
    }

    /*
     * Signals we do not care about are passed through untouched.
     */
    if (!is_special_signal(signum))
        return real_sigaction(signum, act, oldact);

    /*
     * Keep sigaction(signum, NULL, &oldact) transparent.
     * The kernel knows about our wrapper, but callers must continue
     * seeing the original handler that we replaced.
     */
    if (!act)
    {
        struct sigaction kernel_old;
        struct sigaction *saved;
        int *have_saved;
        int ret;

        if (!oldact)
            return real_sigaction(signum, NULL, NULL);

        memset(&kernel_old, 0, sizeof(kernel_old));

        ret = real_sigaction(signum, NULL, &kernel_old);

        if (ret != 0)
            return ret;

        saved = saved_action_for_signal(signum);
        have_saved = saved_flag_for_signal(signum);

        if (kernel_action_is_our_wrapper(signum, &kernel_old) &&
            saved &&
            have_saved &&
            *have_saved)
        {
            *oldact = *saved;
        }
        else
        {
            *oldact = kernel_old;
        }

        return 0;
    }

    if (act->sa_flags & SA_SIGINFO)
    {
        linuwux_log(
            "observed sigaction(%s), handler=%p flags=%#x",
            signum == SIGSEGV ? "SIGSEGV" : "SIGSYS",
            (void *)act->sa_sigaction,
            act->sa_flags
        );
    }
    else
    {
        linuwux_log(
            "observed sigaction(%s), handler=%p flags=%#x",
            signum == SIGSEGV ? "SIGSEGV" : "SIGSYS",
            (void *)act->sa_handler,
            act->sa_flags
        );
    }

    /*
     * SIG_DFL, SIG_IGN and empty handlers must remain genuine kernel
     * dispositions. Do not wrap them.
     */
    if (!action_has_real_handler(act))
    {
        saved = saved_action_for_signal(signum);
        have_saved = saved_flag_for_signal(signum);

        if (saved && have_saved)
            *have_saved = 0;

        return real_sigaction(signum, act, oldact);
    }

    saved = saved_action_for_signal(signum);
    have_saved = saved_flag_for_signal(signum);

    if (!saved || !have_saved)
        return real_sigaction(signum, act, oldact);

    previous_saved = *saved;
    previous_have_saved = *have_saved;

    wrapped = *act;
    wrapped.sa_flags |= SA_SIGINFO;
    wrapped.sa_sigaction = wrapper_for_signal(signum);

    memset(&kernel_old, 0, sizeof(kernel_old));

    ret = real_sigaction(
        signum,
        &wrapped,
        oldact ? &kernel_old : NULL
    );

    if (ret != 0)
        return ret;

    /*
     * Preserve the caller-visible oldact semantics. If the kernel's
     * previous handler was already our wrapper, expose the original
     * handler we had saved instead.
     */
    if (oldact)
    {
        if (kernel_action_is_our_wrapper(signum, &kernel_old) &&
            previous_have_saved)
        {
            *oldact = previous_saved;
        }
        else
        {
            *oldact = kernel_old;
        }
    }

    *saved = *act;
    *have_saved = 1;

    /*
     * Wine's signal handlers are installed in normal execution
     * context, not from inside our SIGSEGV/SIGSYS wrappers.
     *
     * At this point ntdll.so may already be available. If it is,
     * ensure the LinUwUx hardware-profile GUID exists. A later
     * special-signal registration retries if ntdll was not ready.
     */
    (void)linuwux_registry_ensure_hwprofileguid();

    if (signum == SIGSEGV)
    {
        (void)linuwux_kuser_init();

        if (linuwux_cpuid_init() == 0)
            (void)linuwux_cpuid_enable_faulting();
    }

    if (act->sa_flags & SA_SIGINFO)
    {
        linuwux_log(
            "installed %s wrapper, original handler=%p",
            signum == SIGSEGV ? "SIGSEGV" : "SIGSYS",
            (void *)act->sa_sigaction
        );
    }
    else
    {
        linuwux_log(
            "installed %s wrapper, original handler=%p",
            signum == SIGSEGV ? "SIGSEGV" : "SIGSYS",
            (void *)act->sa_handler
        );
    }

    return 0;
}
